### ISSUE TITLE
Support for strings in template args

### ISSUE THREAD

**Issue by sudo-panda** [compiler-research/cppyy-backend#25]
wlav/cppyy supports strings in template arguments:

```python
cppyy.cppdef("""
    template <typename T>
    class C {};
""");

cppyy.gbl.C['C<int>']
```

@wlav do we keep this support or supporting the statement underneath is enough:

```python
cppyy.gbl.C[cppyy.gbl.C['int']]
```

**Comment by wlav** [comment]
Strings should be supported as it is often convenient (e.g. simply `"double"` v.s. `cppyy.gbl.double`) and sometimes necessary (e.g. if the C++ class contains names that are Python keywords).

Interesting, too, that even in your example you write `cppyy.gbl.C['int']` instead of `cppyy.gbl.C[int]`. :)

**Comment by sudo-panda** [comment]
> Strings should be supported as it is often convenient (e.g. simply `"double"` v.s. `cppyy.gbl.double`) and sometimes necessary (e.g. if the C++ class contains names that are Python keywords).
> 
> Interesting, too, that even in your example you write `cppyy.gbl.C['int']` instead of `cppyy.gbl.C[int]`. :)

Yes we already support strings for built-in types like int but it's not ideal to support it for classes.

**Comment by vgvassilev** [comment]
I see the point for builtins. The problem becomes interesting when there are template instantiation request or other generic C++ code. That seems more like an escape hatch which takes a performance hit due to the fact that we need to parse it instead just rewiring some already existing handles.

**Comment by wlav** [comment]
I don't understand ... if you have the string, you have the full class name from the get-go, no further parsing or other trouble required? I can see how from class names you can get the decls and then to the instantiation, but what if it's already done?

Template names can get very weird, to. See this test as an example: https://github.com/wlav/cppyy/blob/master/test/test_templates.py#L893

Would highly recommend staying away from parsing whenever possible. :)

**Comment by sudo-panda** [comment]
Yes
