### ISSUE TITLE
Replace gInterpreter with gCling 

### ISSUE THREAD

**Issue by sudo-panda** [compiler-research/cppyy-backend#6]
Current status: Some functions in gCling are not supported in Cppyy. FIXME's for the same have been added. See: https://github.com/sudo-panda/cppyy/commit/76681028f7d861b1a77a68d3fdf2d2b165f0f3cc

**Comment by vgvassilev** [comment]
Shouldn't we provide an alias to `gInterpreter` pointing to `gCling`? This way we will be backward compatible with older codes.

**Comment by sudo-panda** [comment]
> Shouldn't we provide an alias to `gInterpreter` pointing to `gCling`? This way we will be backward compatible with older codes.

Just providing an alias wouldn't work as `gCling` functions do not have the exact same name and functionality. If we want to make it backwards compatible we will need to create a class that wraps around `gCling` and provides the functions that `gInterpreter` has.

**Comment by vgvassilev** [comment]
We probably need @wlav’s take on this.

**Comment by wlav** [comment]
`gInterpreter` was never originally supported and can be dropped as long as we do a major cppyy upgrade (e.g. 4.0.0). For methods of it that were supported, there was always a wrapper (e.g. `cppdef`).

I do like the `runtime`, but `runtime.gCling` seems overkill. Python being Python, all methods can simply be in `runtime`. Or call that `cling` if you want to have that name up front for clarity.

**Comment by wlav** [comment]
Fine too, although I like the all lower-case. And yes (I only count 15 tests anyway, with almost all simply to get the c++ version number, as access to gInterpreter has never been documented as a supported feature).

**Comment by vgvassilev** [comment]
This issue was resolved in a different way by exposing `InterOp.*` interfaces.
